# Configuration Prometheus
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1


scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http

    static_configs:
      # Cible de scraping (ici en local)
      - targets:
          - localhost:9090
          - node-exporter:9100
          #- joomla:8080

  # Apache Servers
  - job_name: apache
    static_configs:
      - targets:
        - monitoring_apache:9117